---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata15
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Note: we can do more complex init with a shell script (i.e. multiple DBs, multiple users) but setting passwords for
# them all gets a bit gnarly as it would involve mounting multiple things into the entrypoint dir and I'm not sure
# I'm ready for that. (Could also load that as a secret but I don't want to change the structure here too much - had
# this as an example and wanted to make sure I could use the scheme)
kind: ConfigMap
apiVersion: v1
metadata:
  name: dbinit
data:
  dbinit.sql: |-
    \c coffeeshop;
    DROP SCHEMA IF EXISTS inventory CASCADE;
    CREATE SCHEMA inventory AUTHORIZATION coffeeshop;
    DROP SCHEMA IF EXISTS coffeeshop CASCADE;
    CREATE SCHEMA coffeeshop AUTHORIZATION coffeeshop;
    DROP SCHEMA IF EXISTS kitchen CASCADE;
    CREATE SCHEMA kitchen AUTHORIZATION coffeeshop;
    DROP SCHEMA IF EXISTS barista CASCADE;
    CREATE SCHEMA barista AUTHORIZATION coffeeshop;
    alter table if exists coffeeshop.LineItems
      drop constraint if exists FK6fhxopytha3nnbpbfmpiv4xgn;
    drop table if exists coffeeshop.LineItems cascade;
    drop table if exists coffeeshop.Orders cascade;
    drop table if exists coffeeshop.OutboxEvent cascade;
    create table coffeeshop.LineItems (
                                 itemId varchar(255) not null,
                                 item varchar(255),
                                 lineItemStatus varchar(255),
                                 name varchar(255),
                                 price numeric(19, 2),
                                 order_id varchar(255) not null,
                                 primary key (itemId)
    );
    create table coffeeshop.Orders (
                              order_id varchar(255) not null,
                              loyaltyMemberId varchar(255),
                              location     varchar(255),
                              orderSource varchar(255),
                              orderStatus varchar(255),
                              timestamp timestamp,
                              primary key (order_id)
    );
    create table coffeeshop.OutboxEvent (
                                   id uuid not null,
                                   aggregatetype varchar(255) not null,
                                   aggregateid varchar(255) not null,
                                   type varchar(255) not null,
                                   timestamp timestamp not null,
                                   payload varchar(8000),
                                   tracingspancontext varchar(256),
                                   primary key (id)
    );
    alter table if exists coffeeshop.LineItems
          add constraint FK6fhxopytha3nnbpbfmpiv4xgn
              foreign key (order_id)
                  references coffeeshop.Orders;

    create sequence inventory.hibernate_sequence start 1 increment 1;
    create table inventory.Inventory (
                                          id int8 not null,
                                          backOrderQuantity int4 not null,
                                          inStockQuantity int4 not null,
                                          lastSaleDate date,
                                          lastStockDate date,
                                          maxRetailPrice float8,
                                          maximumQuantity int4 not null,
                                          minimumQuantity int4 not null,
                                          orderQuantity int4 not null,
                                          reservedQuantity int4 not null,
                                          unitCost float8,
                                          productMaster_sku_id uuid,
                                          primary key (id)
    );
    create table inventory.OutboxEvent (
                                             id uuid not null,
                                             aggregatetype varchar(255) not null,
                                             aggregateid varchar(255) not null,
                                             type varchar(255) not null,
                                             timestamp timestamp not null,
                                             payload varchar(8000),
                                             tracingspancontext varchar(256),
                                             primary key (id)
    );
    create table inventory.ProductMaster (
                                               sku_id uuid not null,
                                               item varchar(256),
                                               primary key (sku_id)
    );
    alter table if exists inventory.Inventory add constraint FK4gqdqmrew97itl6ola2uh50tu
      foreign key (productMaster_sku_id) references inventory.ProductMaster;
    grant all on all tables in schema "coffeeshop" to coffeeshop;
    grant all on all tables in schema "coffeeshop" to coffeeshop;
    grant all on all tables in schema "inventory" to coffeeshop;
    grant all on all tables in schema "inventory" to coffeeshop;
    grant all on all tables in schema "barista" to coffeeshop;
    grant all on all tables in schema "barista" to coffeeshop;
    grant all on all tables in schema "kitchen" to coffeeshop;
    grant all on all tables in schema "kitchen" to coffeeshop;
---
kind: Deployment
apiVersion: v1
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:15
          env:
            - name: POSTGRES_USER
              value: coffeeshop
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: pgdata15
              mountPath: /var/lib/postgresql/data
            - name: dbinit
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pgdata15
          persistentVolumeClaim:
            claimName: pgdata15
        - name: dbinit
          configMap:
            name: dbinit
